server:
  port: 9000 #设置端口号 冒号和数字之间有空格
  servlet:
    context-path: / #设置项目访问路径

spring:
  datasource: #设置数据源信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homestay?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 111111 #自己的密码
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB



mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.homestay.bean
file:
  upload-path: C:\Users\钢铁加鲁鲁\Desktop\upload\homestay #服务器真实路径
  static-access-path: /files/ #映射地址


